#include "cult/analytics/streaming.hpp"
#include <algorithm>
#include <cmath>
#include <numeric>
#include <stdexcept>

namespace cult::analytics {
void OnlineMoments::push(double value) noexcept { ++count_; const double delta=value-mean_; mean_+=delta/static_cast<double>(count_); m2_+=delta*(value-mean_); }
double OnlineMoments::variance() const noexcept { return count_>1?m2_/static_cast<double>(count_-1):0.0; }
Ewma::Ewma(double alpha):alpha_(alpha){if(!(alpha>0.0&&alpha<=1.0))throw std::invalid_argument("EWMA alpha must be in (0,1]");}
double Ewma::push(double value) noexcept { value_=value_?alpha_*value+(1.0-alpha_)*value_.value():value;return value_.value(); }
EwmaMoments::EwmaMoments(double half_life){if(!(half_life>0.0))throw std::invalid_argument("EWMA half-life must be positive");lambda_=std::pow(2.0,-1.0/half_life);}
void EwmaMoments::push(double value)noexcept{if(!mean_){mean_=value;variance_=0.0;return;}const double innovation=value-mean_.value();variance_=lambda_*variance_+(1.0-lambda_)*innovation*innovation;mean_=lambda_*mean_.value()+(1.0-lambda_)*value;}
RollingMoments::RollingMoments(std::size_t capacity):capacity_(capacity){if(capacity==0)throw std::invalid_argument("rolling capacity must be positive");}
void RollingMoments::push(double value){values_.push_back(value);sum_+=value;sum_squares_+=value*value;if(values_.size()>capacity_){const double old=values_.front();values_.pop_front();sum_-=old;sum_squares_-=old*old;}}
double RollingMoments::mean()const noexcept{return values_.empty()?0.0:sum_/static_cast<double>(values_.size());}
double RollingMoments::variance()const noexcept{if(values_.size()<2)return 0.0;const double n=static_cast<double>(values_.size());return std::max(0.0,(sum_squares_-sum_*sum_/n)/(n-1.0));}
double RollingMoments::volatility()const noexcept{return std::sqrt(variance());}
RollingCovariance::RollingCovariance(std::size_t capacity):capacity_(capacity){if(capacity==0)throw std::invalid_argument("rolling capacity must be positive");}
void RollingCovariance::push(double x,double y){values_.emplace_back(x,y);sx_+=x;sy_+=y;sxx_+=x*x;syy_+=y*y;sxy_+=x*y;if(values_.size()>capacity_){const auto [ox,oy]=values_.front();values_.pop_front();sx_-=ox;sy_-=oy;sxx_-=ox*ox;syy_-=oy*oy;sxy_-=ox*oy;}}
double RollingCovariance::covariance()const noexcept{const double n=static_cast<double>(values_.size());return n<2.0?0.0:(sxy_-sx_*sy_/n)/(n-1.0);}
double RollingCovariance::correlation()const noexcept{const double n=static_cast<double>(values_.size());if(n<2.0)return 0.0;const double vx=(sxx_-sx_*sx_/n)/(n-1.0),vy=(syy_-sy_*sy_/n)/(n-1.0),den=std::sqrt(std::max(0.0,vx*vy));return den>0.0?covariance()/den:0.0;}
double RollingCovariance::beta()const noexcept{const double n=static_cast<double>(values_.size());if(n<2.0)return 0.0;const double vy=(syy_-sy_*sy_/n)/(n-1.0);return vy>0.0?covariance()/vy:0.0;}
std::vector<double> simple_returns(std::span<const double> v){std::vector<double> out;out.reserve(v.size()>0?v.size()-1:0);for(std::size_t i=1;i<v.size();++i)out.push_back(v[i]/v[i-1]-1.0);return out;}
std::vector<double> log_returns(std::span<const double> v){std::vector<double> out;out.reserve(v.size()>0?v.size()-1:0);for(std::size_t i=1;i<v.size();++i){if(v[i]<=0.0||v[i-1]<=0.0)throw std::domain_error("log returns require positive values");out.push_back(std::log(v[i]/v[i-1]));}return out;}
double momentum(std::span<const double> v,std::size_t p){return v.size()<=p?0.0:v.back()/v[v.size()-p-1]-1.0;}
double sample_variance(std::span<const double> v){if(v.size()<2)return 0.0;OnlineMoments m;for(double x:v)m.push(x);return m.variance();}
double sample_volatility(std::span<const double> v){return std::sqrt(sample_variance(v));}
double covariance(std::span<const double>a,std::span<const double>b){const auto n=std::min(a.size(),b.size());if(n<2)return 0.0;OnlineMoments ma,mb;for(std::size_t i=0;i<n;++i){ma.push(a[a.size()-n+i]);mb.push(b[b.size()-n+i]);}double sum=0.0;for(std::size_t i=0;i<n;++i)sum+=(a[a.size()-n+i]-ma.mean())*(b[b.size()-n+i]-mb.mean());return sum/static_cast<double>(n-1);}
double correlation(std::span<const double>a,std::span<const double>b){const auto n=std::min(a.size(),b.size());if(n<2)return 0.0;const auto aa=a.last(n),bb=b.last(n);const double den=sample_volatility(aa)*sample_volatility(bb);return den>0.0?covariance(aa,bb)/den:0.0;}
double beta(std::span<const double>a,std::span<const double>b){const auto n=std::min(a.size(),b.size());if(n<2)return 0.0;const auto bb=b.last(n);const double var=sample_variance(bb);return var>0.0?covariance(a.last(n),bb)/var:0.0;}
Drawdown drawdown(std::span<const double> v){double peak=0.0,current=0.0,maximum=0.0;for(double x:v){peak=std::max(peak,x);current=peak>0.0?x/peak-1.0:0.0;maximum=std::min(maximum,current);}return{current,maximum};}
double z_score(double value,std::span<const double> h){if(h.empty())return 0.0;OnlineMoments m;for(double x:h)m.push(x);const double sd=std::sqrt(m.variance());return sd>0.0?(value-m.mean())/sd:0.0;}
double normalized_entropy(std::span<const double> weights){if(weights.empty())return 0.0;double sum=0.0;std::size_t positive=0;for(double w:weights){if(!std::isfinite(w)||w<0.0)throw std::invalid_argument("entropy weights must be finite and nonnegative");if(w>0.0){sum+=w;++positive;}}if(sum<=0.0||positive<2)return 0.0;double h=0.0;for(double w:weights)if(w>0.0){const double p=w/sum;h-=p*std::log(p);}return h/std::log(static_cast<double>(positive));}
double realized_volatility(std::span<const double> returns,double scale){if(!(scale>0.0))throw std::invalid_argument("volatility scale must be positive");double squares=0.0;for(double value:returns)squares+=value*value;return std::sqrt(scale*squares);}
double autocorrelation(std::span<const double> values,std::size_t lag){if(lag==0||values.size()<=lag)return 0.0;return correlation(values.subspan(lag),values.first(values.size()-lag));}
double robust_z_score(double value,std::span<const double> history){if(history.empty())return 0.0;std::vector<double> ordered(history.begin(),history.end());std::sort(ordered.begin(),ordered.end());const auto median=[](const std::vector<double>& input){const std::size_t middle=input.size()/2;return input.size()%2?input[middle]:(input[middle-1]+input[middle])/2.0;};const double center=median(ordered);std::vector<double> deviations;deviations.reserve(ordered.size());for(double item:ordered)deviations.push_back(std::abs(item-center));std::sort(deviations.begin(),deviations.end());const double mad=median(deviations);return mad>0.0?0.6744897501960817*(value-center)/mad:0.0;}
double spearman_correlation(std::span<const double> lhs,std::span<const double> rhs){if(lhs.size()!=rhs.size()||lhs.size()<2)return 0.0;const auto rank=[](std::span<const double> values){std::vector<std::pair<double,std::size_t>> ordered;ordered.reserve(values.size());for(std::size_t i=0;i<values.size();++i)ordered.emplace_back(values[i],i);std::sort(ordered.begin(),ordered.end());std::vector<double> ranks(values.size());for(std::size_t start=0;start<ordered.size();){std::size_t end=start+1;while(end<ordered.size()&&ordered[end].first==ordered[start].first)++end;const double value=(static_cast<double>(start+end-1)/2.0)+1.0;for(std::size_t i=start;i<end;++i)ranks[ordered[i].second]=value;start=end;}return ranks;};const auto left=rank(lhs),right=rank(rhs);return correlation(left,right);}
MarketFactors market_factors(std::span<const double> returns,std::span<const double> weights){if(returns.size()!=weights.size()||returns.empty())throw std::invalid_argument("market inputs must be aligned");double total=0.0;for(double weight:weights){if(weight<0.0)throw std::invalid_argument("market weights must be nonnegative");total+=weight;}if(!(total>0.0))throw std::invalid_argument("market weights must sum positive");MarketFactors output;std::vector<double> normalized;normalized.reserve(weights.size());for(double weight:weights)normalized.push_back(weight/total);for(std::size_t i=0;i<returns.size();++i){output.market_return+=normalized[i]*returns[i];if(returns[i]>0.0)output.breadth+=1.0/static_cast<double>(returns.size());output.hhi+=normalized[i]*normalized[i];}for(std::size_t i=0;i<returns.size();++i){const double difference=returns[i]-output.market_return;output.dispersion+=normalized[i]*difference*difference;}output.dispersion=std::sqrt(output.dispersion);output.effective_expression_count=output.hhi>0.0?1.0/output.hhi:0.0;output.normalized_entropy=normalized_entropy(normalized);return output;}
}
