"""Generate Report 001 only from an immutable snapshot; never invent findings."""
from __future__ import annotations
import argparse
from datetime import datetime
import json
from pathlib import Path
import pandas as pd

parser = argparse.ArgumentParser()
parser.add_argument("dataset")
parser.add_argument("output")
args = parser.parse_args()
root = Path(args.dataset)
manifest = json.loads((root / "manifest.json").read_text(encoding="utf-8"))
duration = (datetime.fromisoformat(manifest["end"].replace("Z", "+00:00")) - datetime.fromisoformat(manifest["start"].replace("Z", "+00:00"))).total_seconds() / 86400
tables = manifest.get("tables", {})
status = "EMPIRICAL" if duration >= 7 else "COVERAGE_ONLY_INSUFFICIENT_HISTORY"
lines = ["# CULT Expression Market Report 001", "", "## Statistical Structure of Public Emoji Expression on Bluesky", "", f"Status: **{status}**", "", f"Dataset: `{manifest['dataset_id']}`", f"Coverage: {duration:.2f} days", f"Methodology: `{manifest['methodology_version']}`", f"Registry: `{manifest['registry_version']}`", "", "CULT measures public expression inside COIP; it does not measure humanity or the entire internet.", ""]
if duration < 7:
    lines += ["## Result policy", "", "The dataset has fewer than seven complete days. Inferential sections are intentionally withheld; no momentum, seasonality, correlation, PCA, pair, or predictive claim is published.", ""]
else:
    prevalence_path = root / "expression_prevalence.parquet"
    if prevalence_path.exists():
        frame = pd.read_parquet(prevalence_path)
        lines += ["## Data coverage", "", f"Rows: {len(frame):,}", "", "The remaining empirical sections must be generated by registered experiment outputs; absence is reported rather than filled with synthetic conclusions.", ""]
lines += ["## Dataset tables", ""] + [f"- `{name}`: {metadata['rows']:,} rows, SHA-256 `{metadata['sha256']}`" for name, metadata in sorted(tables.items())] + ["", "## Limitations", "", "Single-source COIP coverage is provisional. Public Bluesky users are a non-probability sample. Correlation, prediction, Granger predictability, event association, and causal effects are distinct claims."]
Path(args.output).write_text("\n".join(lines) + "\n", encoding="utf-8")
