import type { IndexDefinition } from '@cult/shared';
export type Weighting=IndexDefinition['weighting'];
export function calculateWeights(attention:number[],method:Weighting='EQUAL',cap=1){if(!attention.length)return[];const raw=method==='EQUAL'?attention.map(()=>1):method==='SQRT_ATTENTION_WEIGHTED'?attention.map(x=>Math.sqrt(Math.max(0,x))):attention.map(x=>Math.max(0,x));let weights=normalize(raw);for(let pass=0;pass<attention.length&&weights.some(x=>x>cap+1e-12);pass++){const excess=weights.reduce((s,x)=>s+Math.max(0,x-cap),0),uncapped=weights.map((x,i)=>x<cap?i:-1).filter(i=>i>=0);weights=weights.map(x=>Math.min(x,cap));const base=uncapped.reduce((s,i)=>s+weights[i]!,0);for(const i of uncapped)weights[i]!+=base?excess*weights[i]!/base:excess/uncapped.length;}return normalize(weights);}
const normalize=(xs:number[])=>{const sum=xs.reduce((a,b)=>a+b,0);return sum?xs.map(x=>x/sum):xs.map(()=>1/xs.length);};
export const indexValue=(base:number,basePrices:Record<string,number>,prices:Record<string,number>,constituents:{assetId:string;weight:number}[])=>base*constituents.reduce((s,c)=>s+c.weight*(prices[c.assetId]??basePrices[c.assetId]??0)/(basePrices[c.assetId]??1),0);
export interface CompositionSnapshot { effectiveAt:string; constituents:ReadonlyArray<{assetId:string;weight:number}> }
export class IndexHistory { private snapshots:CompositionSnapshot[]=[];rebalance(snapshot:CompositionSnapshot){if(this.snapshots.some(x=>x.effectiveAt===snapshot.effectiveAt))throw new Error('Composition already frozen');const constituents:ReadonlyArray<{assetId:string;weight:number}>=Object.freeze(snapshot.constituents.map(c=>Object.freeze({...c})));this.snapshots.push(Object.freeze({effectiveAt:snapshot.effectiveAt,constituents}));this.snapshots.sort((a,b)=>a.effectiveAt.localeCompare(b.effectiveAt));}compositionAt(timestamp:string){return [...this.snapshots].reverse().find(x=>x.effectiveAt<=timestamp);}}
export const INDEXES:IndexDefinition[]=[
 ['emoji100','EMOJI100','Emoji 100','Broad expression benchmark',10281,1.9,['expr_heart','expr_crying_face','expr_skull','expr_joy','expr_fire']],['brainrot20','BRAINROT20','Brainrot 20','High-momentum language complex',8192,7.3,['expr_cooked','expr_skull','expr_lmao','expr_bruh','expr_mind']],['humor10','HUMOR10','Humor 10','Humor-factor expressions',4292,-1.2,['expr_joy','expr_lmao','expr_skull','expr_clown']],['doom10','DOOM10','Doom 10','Pessimism-factor expressions',5182,8.9,['expr_cooked','expr_over','expr_wilt','expr_l']],['euphoria10','EUPHORIA10','Euphoria 10','Hype and optimism factor',6882,11.2,['expr_fire','expr_rocket','expr_back','expr_w']],['romance10','ROMANCE10','Romance 10','Affection-factor expressions',3811,.8,['expr_heart','expr_pray','expr_wilt']]
].map(([id,ticker,name,description,currentValue,dailyChange,ids])=>({id:id as string,ticker:ticker as string,name:name as string,description:description as string,currentValue:currentValue as number,dailyChange:dailyChange as number,methodology:'Rules-based selection using attention, momentum, breadth, persistence, and cross-platform agreement. Maximum constituent weight 30%.',weighting:'EQUAL',constituents:(ids as string[]).map(assetId=>({assetId,weight:1/(ids as string[]).length})),rebalanceFrequency:'MONTHLY'}));
