import { createServer,type IncomingMessage,type ServerResponse } from 'node:http';
import { ASSETS,PLATFORMS } from '@cult/shared';
import { generateSynthetic } from '@cult/expression-engine';
import { INDEXES } from '@cult/index-engine';
import { SimulatedMarket } from '@cult/market-engine';
import { beta,correlation,logReturns,momentum,runBacktest,momentumStrategy,zScore,volatility } from '@cult/analytics';
import { z } from 'zod';
const port=Number(process.env.PORT??4100),data=generateSynthetic(),prices=Object.fromEntries(ASSETS.map(a=>[a.id,a.marketPrice])),market=new SimulatedMarket(1_000_000n,prices),started=Date.now();
const user={id:'user_demo',username:'cryingcapital',email:'demo@cult.local',subscriptionTier:'ANALYST',bankruptcies:2,bailoutsReceived:1,tradesCompleted:0,createdAt:'2026-01-01T00:00:00Z'};
const orderSchema=z.object({assetId:z.string().min(1),side:z.enum(['BUY','SELL','SHORT','COVER']),quantity:z.number().positive().max(10000)});
const authSchema=z.object({email:z.string().email(),username:z.string().min(2).optional()});
const json=(res:ServerResponse,status:number,body:unknown)=>{res.writeHead(status,{'content-type':'application/json','access-control-allow-origin':process.env.WEB_ORIGIN??'http://localhost:5173','access-control-allow-credentials':'true','access-control-allow-headers':'content-type','access-control-allow-methods':'GET,POST,OPTIONS','x-content-type-options':'nosniff'});res.end(JSON.stringify(body,(_,v)=>typeof v==='bigint'?v.toString():v));};
const readBody=async(req:IncomingMessage)=>{let body='';for await(const chunk of req)body+=chunk;if(body.length>100_000)throw new Error('Payload too large');return JSON.parse(body||'{}');};
const assetByTicker=(ticker:string)=>ASSETS.find(a=>a.ticker===ticker.toUpperCase());
function assetAnalytics(id:string){const points=data.history[id]??[],values=points.map(x=>x.indexValue),rets=logReturns(values),benchmark=data.history.expr_heart!.map(x=>x.indexValue);return {momentum:{d1:momentum(values,1),d7:momentum(values,7),d30:momentum(values,30),d90:momentum(values,90)},volatility:{d7:volatility(rets.slice(-7))*Math.sqrt(365),d30:volatility(rets.slice(-30))*Math.sqrt(365),d90:volatility(rets.slice(-90))*Math.sqrt(365)},betaHeart:beta(rets.slice(-90),logReturns(benchmark).slice(-90)),drawdown:Math.min(...values.map((x,i)=>x/Math.max(...values.slice(0,i+1))-1))};}
const routes=async(req:IncomingMessage,res:ServerResponse)=>{if(req.method==='OPTIONS')return json(res,204,null);const url=new URL(req.url??'/','http://localhost'),path=url.pathname;
 if(path==='/health')return json(res,200,{status:'ok',uptimeSeconds:Math.floor((Date.now()-started)/1000),datasetSeed:data.seed});
 if(path==='/api/v1/auth/session')return json(res,200,{user});
 if(path==='/api/v1/auth/login'||path==='/api/v1/auth/register'){const parsed=authSchema.safeParse(await readBody(req));if(!parsed.success)return json(res,400,{error:'Invalid account details',issues:parsed.error.issues});res.setHeader('set-cookie','cult_session=demo; HttpOnly; SameSite=Lax; Path=/; Max-Age=2592000');return json(res,200,{user:{...user,...parsed.data}});}
 if(path==='/api/v1/assets'&&req.method==='GET')return json(res,200,{data:ASSETS});
 const match=path.match(/^\/api\/v1\/assets\/([^/]+)(?:\/(history|platforms|semantics))?$/);if(match){const asset=assetByTicker(match[1]!);if(!asset)return json(res,404,{error:'Expression not listed'});const part=match[2];if(part==='history')return json(res,200,{data:data.history[asset.id],events:data.events.filter(e=>e.assets.includes(asset.id))});if(part==='platforms'){const latest=Object.fromEntries(PLATFORMS.map(p=>[p,data.observations.filter(o=>o.expressionId===asset.id&&o.platform===p).at(-1)]));return json(res,200,{data:latest});}if(part==='semantics')return json(res,200,{data:data.semantics[asset.id]});return json(res,200,{data:{...asset,analytics:assetAnalytics(asset.id),latestSemantics:data.semantics[asset.id]?.at(-1)}});}
 if(path==='/api/v1/indexes')return json(res,200,{data:INDEXES});const im=path.match(/^\/api\/v1\/indexes\/([^/]+)$/);if(im){const index=INDEXES.find(x=>x.ticker===im[1]!.toUpperCase());if(!index)return json(res,404,{error:'Index not found'});const hist=data.history[index.constituents[0]!.assetId]!.map((p,i)=>({timestamp:p.timestamp,value:index.currentValue*index.constituents.reduce((s,c)=>s+c.weight*(data.history[c.assetId]?.[i]?.indexValue??1)/(data.history[c.assetId]?.at(-1)?.indexValue??1),0)}));return json(res,200,{data:{...index,history:hist}});}
 if(path==='/api/v1/portfolio')return json(res,200,{data:{...market.portfolio(),user,bankruptcies:user.bankruptcies,achievements:['DIAMOND HANDS','DIVERSIFICATION IS FOR COWARDS'],orders:market.orders.slice(-10).reverse()}});
 if(path==='/api/v1/orders'&&req.method==='GET')return json(res,200,{data:market.orders});if(path==='/api/v1/orders'&&req.method==='POST'){const parsed=orderSchema.safeParse(await readBody(req));if(!parsed.success)return json(res,400,{error:'Invalid order',issues:parsed.error.issues});try{const order=market.submitOrder({...parsed.data,userId:user.id});user.tradesCompleted++;return json(res,201,{data:order,portfolio:market.portfolio()});}catch(error){return json(res,422,{error:error instanceof Error?error.message:'Order rejected'});}}
 if(path==='/api/v1/leaderboard')return json(res,200,{data:[['syntaxerror',84.2,18420,0,421],['cryingcapital',41.8,market.portfolio().value,2,user.tradesCompleted],['doomresearch',26.4,12640,4,88],['hearthedge',18.1,11810,0,37],['bruhmoment',-8.2,9180,7,612]].map(([username,twr,value,bankruptcies,trades],i)=>({rank:i+1,username,twr,value,bankruptcies,trades}))});
 if(path==='/api/v1/analytics/pair'){const a=assetByTicker(url.searchParams.get('a')??'CRY'),b=assetByTicker(url.searchParams.get('b')??'SKULL');if(!a||!b)return json(res,400,{error:'Unknown pair'});const ah=data.history[a.id]!,bh=data.history[b.id]!,ratio=ah.map((x,i)=>x.indexValue/bh[i]!.indexValue),ar=logReturns(ah.map(x=>x.indexValue)),br=logReturns(bh.map(x=>x.indexValue));return json(res,200,{data:{a,b,series:ah.map((x,i)=>({timestamp:x.timestamp,ratio:ratio[i],spread:x.indexValue-bh[i]!.indexValue})),correlation:correlation(ar.slice(-90),br.slice(-90)),relativeMomentum:momentum(ah.map(x=>x.indexValue),30)-momentum(bh.map(x=>x.indexValue),30),zScore:zScore(ratio.at(-1)!,ratio.slice(-90)),relativeVolatility:volatility(ar.slice(-30))-volatility(br.slice(-30))}});}
 if(path==='/api/v1/analytics/correlation'){const ids=ASSETS.slice(0,10);return json(res,200,{data:ids.map(a=>({ticker:a.ticker,values:ids.map(b=>correlation(logReturns(data.history[a.id]!.map(x=>x.indexValue)).slice(-90),logReturns(data.history[b.id]!.map(x=>x.indexValue)).slice(-90)))}))});}
 if(path==='/api/v1/backtests'&&req.method==='POST'){const bars=data.history.expr_crying_face!.map((p,i)=>({timestamp:p.timestamp,prices:Object.fromEntries(ASSETS.map(a=>[a.id,data.history[a.id]?.[i]?.marketPrice??a.marketPrice]))})),result=runBacktest(bars,momentumStrategy(ASSETS.map(a=>a.id),30),{initialCash:10000,feeRate:.001,rebalanceEvery:7});return json(res,201,{data:{id:'bt_demo',strategy:'Top 3 / 30-day momentum',...result,limitations:['Synthetic daily closes','No market impact','No short borrow costs']}});}
 if(path==='/api/v1/events')return json(res,200,{data:data.events});
 if(path==='/api/v1/research')return json(res,200,{data:[{title:'Initiating Coverage: 😂 — UNDERPERFORM',author:'CULT Research',summary:'Legacy laughter remains under pressure as humor share migrates toward 💀 and 😭.',publishedAt:'2026-08-18T14:00:00Z',assetsCovered:['JOY','SKULL','CRY'],views:1842,likes:211}]});
 return json(res,404,{error:'Route not found'});
};
createServer((req,res)=>{const requestId=crypto.randomUUID();const began=Date.now();routes(req,res).catch(error=>json(res,500,{error:'Internal server error',requestId})).finally(()=>console.log(JSON.stringify({level:'info',requestId,method:req.method,path:req.url,status:res.statusCode,durationMs:Date.now()-began})));}).listen(port,()=>console.log(JSON.stringify({level:'info',message:'CULT API ready',port})));
